### ISSUE TITLE
Create Asset Model

### ISSUE THREAD

**Issue by jrthreadgill** [TheGnarCo/GEAR#20]
Create a data model for the application

**Comment by stevemeisner** [comment]
Proposed initial asset `type` enum:

```rb
enum type: {
    laptop: 0,
    display: 1,
    keyboard: 2,
    mouse: 3,
    power_supply: 4,
    desk: 5,
    chair: 6,
    other: 7,
  }
```

I am thinking about adding an optional description field to the asset model. This could be particularly useful when we have an asset in "other". Thoughts?

**Comment by efertsch** [comment]
> I am thinking about adding an optional description field to the asset model. This could be particularly useful when we have an asset in "other". Thoughts?

I wouldn't be opposed to that, and it could be a good exercise to implement a conditional validation on that i.e. `description` must be present if `type` is `other`. 

I am curious what the "other" type might be though. It also seems like we want to be pretty specific with our cataloging (since it is inventory) so if it is _not_ one of the first 6 items in this hash, should we add an enum value for it instead of lumping it in with "other"?

**Comment by efertsch** [comment]
Also, I _think_ `type` might be a reserved keyword. I could be wrong about that but it might be worth checking out 😄

**Comment by alxjrvs** [comment]
It is - for polymorphic types (n o)

**Comment by stevemeisner** [comment]
>  for polymorphic types (n o)

@alxjrvs at first, I thought that you were making an old school emoji ʕʘ̅͜ʘ̅ʔ

I'm curious what that actually means :-)

**Comment by stevemeisner** [comment]
There is a notion of an "active" or "retired" asset. Should this be another `enum` on the Asset model?

**Comment by efertsch** [comment]
> There is a notion of an "active" or "retired" asset. Should this be another `enum` on the Asset model?

Yes, maybe something like `status`?

**Comment by alxjrvs** [comment]
@efertsch @stevemeisner What about a `retired_at` timestamp?

**Comment by alxjrvs** [comment]
We could make a scope for `active` and `retired` keyed off of the presence of `retired_at`. Admittedly, enums do that for us as well, but timestamps do give us that extra bit of data.

**Comment by alxjrvs** [comment]
@stevemeisner Re: "Polymorphic" - I actually got my terms mixed up here. The Thing I was thinking of was "Single Table Inheritance", which is when you create several distinct Rails Models that all share a common database table, allowing you to inherit behaviors amongst ActiveRecord based models. 

Check [this out](https://medium.com/@GeneHFang/single-table-inheritance-in-rails-6-emulating-oop-principles-in-relational-databases-be60c84e0126) for more of what I mean!

**Comment by efertsch** [comment]
> @efertsch @stevemeisner What about a `retired_at` timestamp?

I like that idea. Are there cases to account for where items are returned but not necessarily retired?

**Comment by alxjrvs** [comment]
I don't hate it, but we could keep it simple for now. Maybe "laptop" and
"desk" for start? Or "laptop" and "misc"?

**Comment by alxjrvs** [comment]
I do like the description field, though!

And yeah, given that this is internal to a dev company, I think having it
be an enum is almost more of a feature :p

If it ever becomes an issue, we can always make it more complicated later.
